Update check_ASDF.yml

diff --git a/.github/workflows/check_ASDF.yml b/.github/workflows/check_ASDF.yml
--- a/.github/workflows/check_ASDF.yml
+++ b/.github/workflows/check_ASDF.yml
@@ -19,3 +19,14 @@ jobs:
           echo "Error: ASDF found in src/App.js. Please remove it before merging."
           exit 1
         fi
+
+    - name: Check for SEARCH_PATTERN in App.js
+      run: |
+        SEARCH_PATTERN=${{ secrets.SEARCH_PATTERN }}
+        
+    - name: Check for pattern in App.js
+      run: |
+        if grep -q "$SEARCH_PATTERN" src/App.js; then
+          echo "Error: '$SEARCH_PATTERN' found in src/App.js. Please remove it before merging."
+          exit 1
+        fi
